version: "2.1"

services:
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
      - "certbot"
    volumes:
      # Allow for the serving of static assets through nginx
      - "./nginx/www:/var/www/html"
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    # reload nginx every 6 hour to pull in a new certificate
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  php:
    build: "./php"
    links: 
      - "redis"
      - "mariadb"
    volumes:
      - "./nginx/www:/var/www/html"
  redis: 
    image: "redis:latest"
    command: "--appendonly yes"
  mariadb:
    image: "mariadb:latest"
    volumes:
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "qq3VUaECCl+ysl"
      MYSQL_DATABASE: paybee
      MYSQL_USER: paybee
      MYSQL_PASSWORD: "G&DZLmE1sUAY"
    ports:
      - "3306"
  certbot:
    image: "certbot/certbot:latest"
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
