version: "2"

services:
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php" 
    # Allow for the serving of static assets through nginx
    volumes:
      - "/var/www/paybee:/var/www/html"
  php:
    build: "./php"
    links: 
      - "redis"
      - "mariadb"
    volumes:
      - "/var/www/paybee:/var/www/html"
  redis: 
    image: "redis:latest"
    command: "--appendonly yes"
  mariadb:
    image: "mariadb:latest"
    volumes:
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "qq3VUaECCl+ysl"
      MYSQL_DATABASE: paybee
      MYSQL_USER: paybee
      MYSQL_PASSWORD: "G&DZLmE1sUAY"
