version: "2.1"

services:
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
      - "certbot"
    # Allow for the serving of static assets through nginx
    volumes:
      - "./nginx/www/paybee:/var/www/html"
      - "./certbot/certificates:/etc/certificates"
      - "./nginx/www/letsencrypt:/var/www/letsencrypt"
    healthcheck:
      test: ["CMD", "test", "-f", "/etc/certificates/live/paybee.co.za/fullchain.pem"]
      interval: 10s
      timeout: 10s
      retries: 20
  php:
    build: "./php"
    links: 
      - "redis"
      - "mariadb"
    volumes:
      - "./nginx/www/paybee:/var/www/html"
  redis: 
    image: "redis:latest"
    command: "--appendonly yes"
  mariadb:
    image: "mariadb:latest"
    volumes:
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "qq3VUaECCl+ysl"
      MYSQL_DATABASE: paybee
      MYSQL_USER: paybee
      MYSQL_PASSWORD: "G&DZLmE1sUAY"
    ports:
      - "3306"
  certbot:
    image: "certbot/certbot:latest"
    volumes:
      - "./certbot/certificates:/etc/certificates"
      - "./nginx/www/letsencrypt:/var/www/.well-known"
    command: "certonly --agree-tos --email marnulombard@gmail.com --renew-by-default --webroot -w /var/www -d paybee.co.za"
